name-template: "Release v${{ nextReleaseVersion }}"
tag-template: "v${{ nextReleaseVersion }}"
categories:
  - title: "🚀 New Features2"
    labels:
      - feature
  - title: "🐛 Bug Fixes2"
    labels:
      - bug
change-template: "- ${{ change }}"
template: |
  ## What's Changed
  $CHANGES
