name-template: "Release v${{ nextReleaseVersion }}"
tag-template: "v${{ nextReleaseVersion }}"
categories:
  - title: "🚀 New Features"
    labels:
      - feature
  - title: "🐛 Bug Fixes"
    labels:
      - bug
change-template: "- ${{ change }}"
template: |
  ## What's Changed
  $CHANGES
