name: app
command:
  bootstrap:
    environment:
      sdk: ">=3.0.0 <4.0.0"
      flutter: ">=3.0.0 <4.0.0"
    dependencies:
      collection: ^1.18.0
    dev_dependencies:
      build_runner: ^2.3.3
packages: 
  - packages/**
  - ./
