name: CI

on:
  push:
  pull_request:

jobs:
  lint-and-test:
    runs-on: ubuntu-latest
    steps:
      - uses: ./.github/actions/setup

      - name: Install dependencies
        run: flutter pub get

      - name: Analyze (Lint)
        run: flutter analyze

      - name: Test
        run: flutter test

      - name: Build
        run: flutter build web --dart-define-from-file=define/dev.json
