name: Release Drafter

on:
  push:
    branches:
      - "feature/*"

jobs:
  update_release_draft:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Release Drafter
        uses: release-drafter/release-drafter@v6
